[tool.poetry]
name = "torch-activation"
version = "1.0.0"
description = "Activation functions for PyTorch"
authors = ["Alan Huynh <hdmquan@outlook.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "torch_activation"}]

[tool.poetry.dependencies]
python = ">=3.10, <4.0"
torch = ">=1.13.0"

[tool.poetry.extras]
plot = ["plotly", "kaleido"]

[tool.poetry.group.dev.dependencies]
pre-commit = "*"
black = "*"
flake8 = "*"
mypy = "*"
isort = "*"
doc8 = "*"
pytest = "^8.3.5"
loguru = "*"
scipy = "^1.15.2"
plotly = "^6.0.0"
kaleido = "0.2"
sphinx = "8.0"

[tool.doc8]
max-line-length = 100
ignore-path = ["docs/_build", "docs/source/activations"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
